Update Structure (#1)
* Update README.md
* fix namespaces
* Update setup-opendxp-environment.sh
* adjust docs
* update workflows
* remove php 8.1 support
* Update LICENSE.md

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -1,4 +1,4 @@
-name: "Static analysis centralised"
+name: Static analysis [centralised]
 
 on:
     schedule:
@@ -12,7 +12,6 @@ on:
     pull_request:
         types: [ opened, synchronize, reopened ]
 
-
 env:
     OPENDXP_PROJECT_ROOT: ${{ github.workspace }}
     PRIVATE_REPO: ${{ github.event.repository.private }}
@@ -25,55 +24,55 @@ jobs:
             matrix: ${{ steps.set-matrix.outputs.matrix }}
             private_repo: ${{ env.PRIVATE_REPO }}
         steps:
-            - name: Checkout code
-              uses: actions/checkout@v4
+            -   name: Checkout code
+                uses: actions/checkout@v4
 
-            - name: Checkout reusable workflow repo
-              uses: actions/checkout@v4
-              with:
-                  repository: open-dxp/workflows-collection-public
-                  ref: main
-                  path: reusable-workflows
+            -   name: Checkout reusable workflow repo
+                uses: actions/checkout@v4
+                with:
+                    repository: open-dxp/workflows-collection-public
+                    ref: main
+                    path: reusable-workflows
 
-            - name: Parse PHP versions from composer.json
-              id: parse-php-versions
-              run: |
-                  if [ -f composer.json ]; then
-                    php_versions=$(jq -r '.require.php' composer.json | grep -oP '\d+\.\d+' | tr '\n' ',' | sed 's/,$//')
-                    if [ -z "$php_versions" ]; then
-                      echo "No PHP versions found in composer.json"
-                      echo "Setting default PHP value"
-                      echo "php_versions=default" >> $GITHUB_OUTPUT
+            -   name: Parse PHP versions from composer.json
+                id: parse-php-versions
+                run: |
+                    if [ -f composer.json ]; then
+                      php_versions=$(jq -r '.require.php' composer.json | grep -oP '\d+\.\d+' | tr '\n' ',' | sed 's/,$//')
+                      if [ -z "$php_versions" ]; then
+                        echo "No PHP versions found in composer.json"
+                        echo "Setting default PHP value"
+                        echo "php_versions=default" >> $GITHUB_OUTPUT
+                      else
+                        echo "php_versions=$php_versions" >> $GITHUB_OUTPUT
+                        echo "#### php versions #### : $php_versions"
+                      fi
                     else
-                      echo "php_versions=$php_versions" >> $GITHUB_OUTPUT
-                      echo "#### php versions #### : $php_versions"
+                      echo "composer.json not found"
+                      exit 1
                     fi
-                  else
-                    echo "composer.json not found"
-                    exit 1
-                  fi
 
-            - name: Set up matrix
-              id: set-matrix
-              run: |
-                  php_versions="${{ steps.parse-php-versions.outputs.php_versions }}"
-                  
-                  MATRIX_JSON=$(cat reusable-workflows/phpstan-configuration/matrix-config.json)
-                  
-                  IFS=',' read -ra VERSIONS_ARRAY <<< "$php_versions"
-                  
-                  FILTERED_MATRIX_JSON=$(echo $MATRIX_JSON | jq --arg php_versions "$php_versions" '
-                  {
-                    matrix: [
-                      .configs[] |
-                      select(.php_version == $php_versions) |
-                      .matrix[]
-                    ]
-                  }')
-                  
-                  ENCODED_MATRIX_JSON=$(echo $FILTERED_MATRIX_JSON | jq -c .)
-                  
-                  echo "matrix=${ENCODED_MATRIX_JSON}" >> $GITHUB_OUTPUT
+            -   name: Set up matrix
+                id: set-matrix
+                run: |
+                    php_versions="${{ steps.parse-php-versions.outputs.php_versions }}"
+                    
+                    MATRIX_JSON=$(cat reusable-workflows/phpstan-configuration/matrix-config.json)
+                    
+                    IFS=',' read -ra VERSIONS_ARRAY <<< "$php_versions"
+                    
+                    FILTERED_MATRIX_JSON=$(echo $MATRIX_JSON | jq --arg php_versions "$php_versions" '
+                    {
+                      matrix: [
+                        .configs[] |
+                        select(.php_version == $php_versions) |
+                        .matrix[]
+                      ]
+                    }')
+                    
+                    ENCODED_MATRIX_JSON=$(echo $FILTERED_MATRIX_JSON | jq -c .)
+                    
+                    echo "matrix=${ENCODED_MATRIX_JSON}" >> $GITHUB_OUTPUT
 
     static-analysis:
         needs: setup-matrix
@@ -90,6 +89,3 @@ jobs:
             EXPERIMENTAL: ${{ matrix.matrix.experimental }}
             OPENDXP_VERSION: ${{ matrix.matrix.opendxp_version }}
             COMPOSER_OPTIONS: ${{ matrix.matrix.composer_options }}
-        secrets:
-            SSH_PRIVATE_KEY_OPENDXP_DEPLOYMENTS_USER: ${{ secrets.SSH_PRIVATE_KEY_OPENDXP_DEPLOYMENTS_USER }}
-            COMPOSER_OPENDXP_REPO_PACKAGIST_TOKEN: ${{ secrets.COMPOSER_OPENDXP_REPO_PACKAGIST_TOKEN }}
